"""initial_schema

Revision ID: a5aa441965dd
Revises: 
Create Date: 2026-08-09 12:48:35.076199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5aa441965dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OHLCV_BARS',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('bar_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('delivery_volume', sa.BigInteger(), nullable=True),
    sa.Column('delivery_pct', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timeframe', 'bar_time')
    )
    op.create_table('STOCKS',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('market_cap_bucket', sa.String(), nullable=True),
    sa.Column('market_cap_cr', sa.Numeric(), nullable=True),
    sa.Column('beta_1y', sa.Numeric(), nullable=True),
    sa.Column('free_float_pct', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_STOCKS_symbol'), 'STOCKS', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_STOCKS_symbol'), table_name='STOCKS')
    op.drop_table('STOCKS')
    op.drop_table('OHLCV_BARS')
    # ### end Alembic commands ###
